In [1]:
import pandas as pd
import os 
import ast

import sklearn as skl
import sklearn.utils, sklearn.preprocessing, sklearn.decomposition, sklearn.svm
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
import numpy as np

Load data

In [2]:
filepath = '../data/fma_metadata/tracks.csv'
tracks = pd.read_csv(filepath, index_col=0, header=[0, 1])
tracks.head()

            album                                                     \
         comments         date_created        date_released engineer
track_id
2               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
3               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
5               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
10              0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN
20              0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN

                                                                          \
         favorites id                                information listens
track_id
2                4  1                                    <p></p>    6073
3                4  1                                    <p></p>    6073
5                4  1                                    <p></p>    6073
10               4  6                                        NaN   47632
20               2  4  <p> "spiritual songs" from Nicky Cook</p>    2710

                        ...       track                         \
         producer tags  ... information interest language_code
track_id                ...
2             NaN   []  ...         NaN     4656            en
3             NaN   []  ...         NaN     1470            en
5             NaN   []  ...         NaN     1933            en
10            NaN   []  ...         NaN    54881            en
20            NaN   []  ...         NaN      978            en

                                                                              \
                                                    license listens lyricist
track_id
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1293      NaN
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...     514      NaN
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1151      NaN
10        Attribution-NonCommercial-NoDerivatives (aka M...   50135      NaN
20        Attribution-NonCommercial-NoDerivatives (aka M...     361      NaN


         number publisher tags            title
track_id
2             3       NaN   []             Food
3             4       NaN   []     Electric Ave
5             6       NaN   []       This World
10            1       NaN   []          Freeway
20            3       NaN   []  Spiritual Level

[5 rows x 52 columns]

In [3]:
keep_cols =  [('set', 'split'), ('set', 'subset'),('track', 'genre_top'), ('track', 'genres')]
tracks = tracks[keep_cols]
tracks.head()

               set             track
             split  subset genre_top     genres
track_id
2         training   small   Hip-Hop       [21]
3         training  medium   Hip-Hop       [21]
5         training   small   Hip-Hop       [21]
10        training   small       Pop       [10]
20        training   large       NaN  [76, 103]

Analyzing MFCC features

In [4]:
filepath = '../data/fma_metadata/features.csv'
features = pd.read_csv(filepath, index_col=0, header=[0, 1, 2], skip_blank_lines=True )

In [5]:
mfcc = features['mfcc']
mfcc.head()

statistics   kurtosis                                                    \
number             01        02        03        04        05        06
track_id
2            3.856789  1.541901  0.000816  0.330728  0.118731 -0.342687
3            4.296755  1.399977  0.112535 -0.211170  0.032953 -0.023489
5            2.624517  2.415293  0.440233 -0.782131 -0.771069 -0.724216
10           5.076893  1.161854  2.095651  1.372743 -0.203574 -0.345354
20          11.880132  4.085320  0.002655  1.518562  0.181947  0.339014

statistics                                          ...        std             \
number            07        08        09        10  ...         11         12
track_id                                            ...
2          -0.259252  0.146735  0.410656 -0.162872  ...  10.059609   8.601942
3           0.150404  0.046454  0.033484 -0.064596  ...   8.771966  10.026867
5           0.090260  0.152119  0.261731 -0.608905  ...   8.863638   9.581952
10         -0.529139  0.561974  0.281350 -0.150672  ...   8.289734   7.985110
20          0.367611  0.069932 -0.016032  0.026012  ...   7.706648   6.498904

statistics                                                              \
number            13        14        15        16        17        18
track_id
2           9.284250  9.245516  8.520863  8.560472  7.651871  7.246555
3           6.978541  7.650417  9.600357  7.222888  8.398293  7.285423
5           8.895723  8.141456  8.201844  7.780963  7.132692  7.539753
10          7.075400  6.972649  7.071393  7.270959  7.051070  6.928591
20          6.845514  6.934421  7.019398  6.983841  6.813648  7.520811

statistics
number            19        20
track_id
2           7.077188  7.391859
3           7.417791  8.777440
5           8.452527  7.334442
10          6.430473  6.186294
20          7.098001  7.032246

[5 rows x 140 columns]

In [6]:
small = tracks['set', 'subset'] == 'small'

train = tracks['set', 'split'] == 'training'
val = tracks['set', 'split'] == 'validation'
test = tracks['set', 'split'] == 'test'

y_train = tracks.loc[small & train, ('track', 'genre_top')]
y_val = tracks.loc[small & val, ('track', 'genre_top')]
y_test = tracks.loc[small & test, ('track', 'genre_top')]

X_train_mfcc = features.loc[small & train, 'mfcc']
X_val_mfcc = features.loc[small & val, 'mfcc']
X_test_mfcc = features.loc[small & test, 'mfcc']

print(f'Training examples: {y_train.size}')

Training examples: 6400

Standarize the features

In [7]:
#Shuffle training features
X_train, y_train = skl.utils.shuffle(X_train_mfcc, y_train, random_state=42)

#Standard Scaling features
scaler = skl.preprocessing.StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val_mfcc)
X_test = scaler.transform(X_test_mfcc)

print(X_train.shape, y_train.shape)

(6400, 140) (6400,)

In [8]:
#Create a label encoder
le = skl.preprocessing.LabelEncoder()

#Fit transform all y's
y_train = le.fit_transform(y_train)
y_val = le.fit_transform(y_val)
y_test = le.fit_transform(y_test)

Building the baseline model

In [9]:
from sklearn.metrics import f1_score
from time import time

In [10]:
def train_classifier(clf, X_train, y_train):
    #Start clock, train model, end clock
    start = time()
    clf.fit(X_train, y_train)
    end = time()
    
    print(f'Elapsed training time: {end - start}')

In [11]:
def predict_labels(clf, features, target):
    
    start = time()
    y_pred = clf.predict(features)
    end = time()
    
    print(f'Elapsed prediction time: {end - start}')
    return f1_score(target, y_pred, average='micro', pos_label=1)

In [12]:
def train_predict(clf, X_train, y_train, X_test, y_test):
    
    #Print classifier being used
    print(f'Training a {clf.__class__.__name__}')
    
    
    #Train the classifier
    train_classifier(clf, X_train, y_train)
    
    #Result of predictions
    print(f'F1 Score for training set: {predict_labels(clf, X_train, y_train)}')
    print(f'F1 Score for testing set: {predict_labels(clf, X_test, y_test)}\n')

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

#Initialize instances of all models
clf_dtc = DecisionTreeClassifier(random_state=10, max_depth=4)
clf_svc = SVC()
clf_lr = LogisticRegression(solver='newton-cg')
clf_rfc = RandomForestClassifier(random_state=10, max_depth=30, n_estimators=300, min_samples_leaf=6, min_impurity_decrease=0.0002,
                     class_weight='balanced')

In [14]:
for clf in [clf_dtc, clf_svc, clf_lr, clf_rfc]:
    print(f'Model: {clf.__class__.__name__}')
    train_predict(clf, X_train, y_train, X_test, y_test)

Model: DecisionTreeClassifier
Training a DecisionTreeClassifier
Elapsed training time: 0.400968074798584
Elapsed prediction time: 0.0018472671508789062
F1 Score for training set: 0.36250000000000004
Elapsed prediction time: 0.0005309581756591797
F1 Score for testing set: 0.28

Model: SVC
Training a SVC
Elapsed training time: 8.083941221237183
Elapsed prediction time: 6.529788970947266
F1 Score for training set: 0.758125
Elapsed prediction time: 0.7982678413391113
F1 Score for testing set: 0.46375

Model: LogisticRegression
Training a LogisticRegression
Elapsed training time: 2.0159900188446045
Elapsed prediction time: 0.0022389888763427734
F1 Score for training set: 0.5621875
Elapsed prediction time: 0.0004451274871826172
F1 Score for testing set: 0.4125

Model: RandomForestClassifier
Training a RandomForestClassifier
Elapsed training time: 13.472323894500732
Elapsed prediction time: 0.41129016876220703
F1 Score for training set: 0.92671875
Elapsed prediction time: 0.06980705261230469
F1 Score for testing set: 0.4375

In [15]:
#Analyzing the best classifier (SVC)

from sklearn.metrics import classification_report

y_pred = clf_svc.predict(X_test)
labels = [0, 1, 2, 3, 4, 5, 6, 7]
target_names = le.inverse_transform(labels)

print(classification_report(y_test, y_pred, target_names=target_names))

               precision    recall  f1-score   support

   Electronic       0.44      0.60      0.51       100
 Experimental       0.34      0.44      0.38       100
         Folk       0.24      0.20      0.22       100
      Hip-Hop       0.63      0.68      0.65       100
 Instrumental       0.51      0.42      0.46       100
International       0.54      0.48      0.51       100
          Pop       0.34      0.25      0.29       100
         Rock       0.66      0.64      0.65       100

     accuracy                           0.46       800
    macro avg       0.46      0.46      0.46       800
 weighted avg       0.46      0.46      0.46       800

In [16]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred))

0.46375

In [17]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[60  9  0 11  4  3  7  6]
 [11 44  6  1 19  5  8  6]
 [ 3 35 20  0  6 17 11  8]
 [13  5  3 68  3  2  3  3]
 [ 5 23 23  0 42  1  6  0]
 [13  1 21 11  1 48  4  1]
 [29  3  8 13  1 12 25  9]
 [ 3  9  4  4  6  1  9 64]]